CREATE TABLE [inc].[BankCardBalans]
(
	[Id] INT PRIMARY KEY IDENTITY(1, 1)
	, [CardId] UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES [inc].[Banks]([Id])
	, [Date] DATE NOT NULL DEFAULT GETDATE()
	, [Balans] MONEY NOT NULL
)
