//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XXWx.Incoms.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCardBalan
    {
        public int Id { get; set; }
        public System.Guid CardId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Balans { get; set; }
    
        public virtual Bank Banks { get; set; }
    }
}
