//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XXWx.Incoms.DAL.EfConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using XXWx.Incoms.Model;
    
    public partial class BankContext : DbContext
    {
        public BankContext()
            : base("name=BankContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual IDbSet<BankCardBalan> BankCardBalans { get; set; }
        public virtual IDbSet<BankCard> BankCards { get; set; }
        public virtual IDbSet<Bank> Banks1 { get; set; }
    }
}
